*
C       Purpose: to solve the Riemann problem exactly
C                for the time dependent and 1D
C                Euler equation for ideal gas
*
        PROGRAM exact

            IMPLICIT NONE
            INTEGER I, CELLS


            REAL GAMMA, G1, G2, G3, G4, G5, G6, G7, G8
            REAL DL, UL, PL, CL, DR, UR, PR, CR 
            REAL DIAPH, DOMLEN, DS, DX, PM, MPA, PS, S
            REAL TIMEOUT, UM, US, XPOS

            COMMON /GAMMAS/ GAMMA,G1,G2,G3,G4,G5,G6,G7,G8
            COMMON /STATES/ DL, UL, PL, CL, DR, UR, PR, CR

            READ(1,*) DOMLEN
            READ(1,*) DIAPH
            READ(1,*) CELLS
            READ(1,*) GAMMA
            READ(1,*) TIMEOUT
            READ(1,*) DL
            READ(1,*) UL
            READ(1,*) PL
            READ(1,*) DR
            READ(1,*) UR
            READ(1,*) PR
            READ(1,*) MPA

            CLOSE(1)

* 
C compute gamma related constants
*

            G1 = (GAMMA-1.0)/(2.0*GAMMA)
            G2 = (GAMMA+1.0)/(2.0*GAMMA)
            G3 = 2.0*GAMMA/(GAMMA-1.0)
            G4 = 2.0/(GAMMA-1.0)
            G5 = 2.0/(GAMMA+1.0)
            G6 = (GAMMA - 1.0) / (GAMMA + 1.0)
            G7 = (GAMMA - 1.0) / 2.0
            G8 = GAMMA - 1.0

* 
C compute sound speeds
*

            CL = SQRT(GAMMA*PL/DL)
            CR = SQRT(GAMMA*PR/DR)

* 
C test the pressure positivity condition
*
            IF(G4*(CL+CR).LE.(UR-UL)) THEN

* 
C initial data shows vacuum is generated
C program stopped
*
                WRITE(6,*)
                WRITE(6,*)'***Vacuum is generated by data***'
                WRITE(6,*)'***Program stopped***'
                WRITE(6,*) 
                STOP 
            ENDIF
* 
C exact solution for pressure and velocity in star region is found
*
            CALL STARPU(PM,UM,MPA)
            DX = DOMLEN/REAL(CELLS)


* 
C Complete solution at times TIMEOUT is found
*
            OPEN(UNIT=2,FILE='exact.out',STATUS='UNKNOWN')

            DO 10 I = 1, CELLS
                XPOS = (REAL(I) - 0.5)*DX
                S    = (XPOS - DIAPH)/TIMEOUT

* 
C Solution at point (X,T) = (XPOS - DIAPH,TIMEOUT)
C is found
*
            CALL SAMPLE(PM,UM,S,DS,US,PS)

* 
C Exact solution profiles are written to exact.out
* 

            WRITE(2,20) XPOS,DS,US,PS/MPA,PS/DS/G8/MPA
  10        CONTINUE
            CLOSE(2)
  20        FORMAT(5(F14.6,2X))

        
        END PROGRAM exact

*
*----------------------------------------------------------------------*
*

        SUBROUTINE STARPU(P,U,MPA)

            IMPLICIT NONE
*
C           Purpose: to compute the solution of pressure and velocity
C           in the star region
*
            INTEGER I, NRITER
            REAL DL, UL, PL, CL, DR, UR, PR, CR
            REAL CHANGE, FL, FLD,FR,FRD, P, POLD, PSTART
            REAL TOLPRE, U, UDIFF, MPA

            COMMON /STATES/ DL, UL, PL, CL, DR, UR, PR, CR
            DATA TOLPRE, NRITER/1.0E-06, 20/

* 
C Guessed value PSTART is required 
*
            CALL GUESSP(PSTART)
            POLD = PSTART
            UDIFF = UR - UL
            WRITE(6,*)'--------------------------------------------'
            WRITE(6,*)'     Iteration number        Change         '
            WRITE(6,*)'--------------------------------------------'

            DO 10 I = 1,NRITER
                CALL PREFUN(FL,FLD, POLD, DL, PL, CL)
                CALL PREFUN(FR,FRD, POLD, DR, PR, CR)
                P = POLD - (FL+FR+UDIFF)/(FLD + FRD)
                CHANGE = 2.0*ABS((P-POLD)/(P+POLD))
                WRITE(6,30) I, CHANGE
                IF(CHANGE.LE.TOLPRE) GOTO 20
                IF(P.LT.0.0) P = TOLPRE
                POLD = P
 10         CONTINUE
            WRITE(6,*)'Divergence in Newton-Raphon iteration'
 20         CONTINUE

* 
C Compute velocity in Star Region
*
            U = 0.5*(UL+UR+FR-FL)
            WRITE(6,*)'--------------------------------------------'
            WRITE(6,*)'     Pressure          Velocity             ' 
            WRITE(6,*)'--------------------------------------------'
            WRITE(6,40)P/MPA, U 
            WRITE(6,*)'--------------------------------------------'

 30         FORMAT(5X, I5, 15X, F12.7)
 40         FORMAT(2(F14.6,5X))
            RETURN 
        END SUBROUTINE STARPU

*
*----------------------------------------------------------------------*
*

        SUBROUTINE GUESSP(PM)

            IMPLICIT NONE
*
C           Purpose: provide guess pressure PM in the Star Region
C                    Sec 9.5 chap 1
*

            REAL DL,UL,PL,CL,DR,UR,PR,CR
            REAL GAMMA,G1,G2,G3,G4,G5,G6,G7,G8
            REAL CUP,GEL,GER,PM,PMAX,PMIN,PPV,PQ
            REAL PTL,PTR,QMAX,QUSER,UM

            COMMON /GAMMAS/ GAMMA,G1,G2,G3,G4,G5,G6,G7,G8
            COMMON /STATES/ DL,UL,PL,CL,DR,UR,PR,CR

            QUSER=2.0

            CUP = 0.25*(DL+DR)*(CL+CR)
            PPV = 0.5



        END SUBROUTINE GUESSP
























